name: website
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -e .;pip install pdoc
      - run: readlink -f ./examples/logo.png
      - run: pdoc --logo ./examples/logo.png -o docs/ fraggler

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deployment
        id: deployment
        uses: actions/checkout@v4
      - uses: actions/deploy-pages@v4

